import greenfoot.*;

/**
 * Main game world
 * 
 * Features
 * - Countdown with overlay and bars
 * - Score management
 * - Timer management
 * - Product spawning
 * 
 * All images are generated by Gemini
 * @author Kolby Ng
 */

public class FactoryWorld extends World  
{
    private GreenfootImage background;
    
    private boolean gameStarted = false;
    
    private int rightProductSpawn = 50;
    private int leftProductSpawn = 50;
    
    private int rightProductQuality = 6;
    private int leftProductQuality = 6;
    
    // Score variables
    private Label leftScoreLabel;
    private Label rightScoreLabel;
    private int leftScore;
    private int rightScore;
    private int labelY = 35;
    private int labelSize = 50;
    private int winCond = 500;
    
    // Bar variables
    private SuperStatBar leftBar;
    private SuperStatBar rightBar;
    private int barProgress = 180;
    private int barHeight = 30;
    
    // Starting timer and countdown variables
    private int startingTimer = 180;
    private Label countdownLabel;
    private int countdownSize = 100;
    private Actor overlay; 
    
    // Starting beep
    private GreenfootSound startingSound;
    
    // Product variables
    private int spawnDelay = 30;
    
    // Left variables
    private Machines leftMach;
    private Hitbox leftAssemblerHitbox;
    private int lastLeft = spawnDelay;
    private int leftPos = 300;

    // Right variables
    private Machines rightMach;
    private Hitbox rightAssemblerHitbox;
    private int lastRight = spawnDelay;
    private int rightPos = 900;
    
    private Machines leftHandler;
    private Machines rightHandler;
    private Machines leftPackager;
    private Machines rightPackager;
    
    // Game timer
    private int timer = 0;
    private Label timerLabel;
    
    // Speed variables
    private double leftSpeed = 4;
    private double rightSpeed = 4;
    
    // Upgrade variables
    private int leftUpgradeX = 50;
    private Break leftBreak;
    private Buy leftBuy;
    private Quality leftQuality;
    private Repair leftRepair;
    private Spawn leftSpawnUpgrade;
    private int leftBrokeRight = -1;
    private int leftUpgradeCooldown = 0;
    
    private int rightUpgradeX = 1150;
    private Break rightBreak;
    private Buy rightBuy;
    private Quality rightQuality;
    private Repair rightRepair;
    private Spawn rightSpawnUpgrade;
    private int rightBrokeLeft = -1;
    private int rightUpgradeCooldown = 0;

    private int spawnUpgradeY = 402;
    private int repairY = 489;
    private int qualityY = 576;
    private int buyY = 663;
    private int breakY = 750;
        
    private boolean leftBoughtPackager = false;
    private boolean rightBoughtPackager = false;
    private boolean leftBoughtHandler = false;
    private boolean rightBoughtHandler = false;
    private Hitbox leftHandlerHitbox;
    private Hitbox rightHandlerHitbox;
    private Hitbox leftPackagerHitbox;
    private Hitbox rightPackagerHitbox;
    
    private int minScoreBuy = 100;
    private int upgradeCooldown = 300;
    private int upgradeChance = 300;
    
    // Pointer variables
    private Pointer leftPointer;
    private Pointer rightPointer;

    private SoundManager soundMan;
    public FactoryWorld(int leftStarting, int rightStarting, int leftQual, int rightQual, int leftRate, int rightRate, SoundManager soundMan)
    {    
        super(1200, 800, 1); 
        
        setPaintOrder(Label.class, BlankActor.class, SuperStatBar.class, Pointer.class, Machines.class, Product.class, Conveyor.class);
        setBackground();
        drawConveyor(leftPos, rightPos);
        setProdQual(leftQual, rightQual);
        setSpawnRate(leftRate, rightRate);
        drawUpgrades();
        drawLabels(leftStarting, rightStarting);
        drawMachines(leftPos, rightPos);
        drawHitboxes(leftPos, rightPos);
        drawCountdown();
        
        this.soundMan = soundMan;
        
        setupPointers();
        
        soundMan.playStarting();
    }
        
    public boolean getStarted(){
        return gameStarted;
    }
    
    public void started(){
        if (gameStarted) {
            //soundMan.playBgm();
            soundMan.playAmbience();
        }
    }
    
    public void stopped(){
        soundMan.pauseStarting();
        // soundMan.pauseBgm();
        soundMan.pauseAmbience();
    }
    
    public void setupPointers(){
        this.leftPointer = new Pointer(soundMan, getWidth() / 8 * 3, getHeight() / 2);
        this.rightPointer = new Pointer(soundMan, getWidth() / 8 * 5, getHeight() / 2);
        addObject(leftPointer, getWidth() / 8 * 3, getHeight() / 2);
        addObject(rightPointer, getWidth() / 8 * 5, getHeight() / 2);
    }
    
    public void setSpawnRate(int leftRate, int rightRate){
        this.leftProductSpawn = leftRate;
        this.rightProductSpawn = rightRate;
    }
    
    public void setProdQual(int leftQual, int rightQual){
        this.leftProductQuality = leftQual;
        this.rightProductQuality = rightQual;
    }
    
    public void drawConveyor (int leftPos, int rightPos){
        addObject(new Conveyor(), leftPos, getHeight() / 2);
        addObject(new Conveyor(), rightPos, getHeight() / 2);
    }
    
    public void drawMachines(int leftPos, int rightPos){
        leftMach = new Assembler();
        rightMach = new Assembler();
        addObject(leftMach, leftPos, getHeight() / 2);
        addObject(rightMach, rightPos, getHeight() / 2);
    }
    
    public void drawHitboxes(int leftPos, int rightPos){
        leftAssemblerHitbox = new Hitbox();
        rightAssemblerHitbox = new Hitbox();
        addObject(leftAssemblerHitbox, leftPos, getHeight() / 2);
        addObject(rightAssemblerHitbox, rightPos, getHeight() / 2);
    }
    
    public void drawUpgrades () {
        leftBreak = new Break(leftUpgradeX);
        leftBuy = new Buy(leftUpgradeX);
        leftQuality = new Quality(leftUpgradeX);
        leftRepair = new Repair(leftUpgradeX);
        leftSpawnUpgrade = new Spawn(leftUpgradeX);
        
        addObject(leftBreak, leftUpgradeX, breakY);
        addObject(leftBuy, leftUpgradeX, buyY);
        addObject(leftQuality, leftUpgradeX, qualityY);
        addObject(leftRepair, leftUpgradeX, repairY);
        addObject(leftSpawnUpgrade, leftUpgradeX, spawnUpgradeY);
        
        rightBreak = new Break(rightUpgradeX);
        rightBuy = new Buy(rightUpgradeX);
        rightQuality = new Quality(rightUpgradeX);
        rightRepair = new Repair(rightUpgradeX);
        rightSpawnUpgrade = new Spawn(rightUpgradeX);
        
        addObject(rightBreak, rightUpgradeX, breakY);
        addObject(rightBuy, rightUpgradeX, buyY);
        addObject(rightQuality, rightUpgradeX, qualityY);
        addObject(rightRepair, rightUpgradeX, repairY);
        addObject(rightSpawnUpgrade, rightUpgradeX, spawnUpgradeY);
    }
    
    public void updateLeftSpawn () {
        leftProductSpawn = Math.max(1, leftProductSpawn - 5);
    }

    public void updateRightSpawn () {
        rightProductSpawn = Math.max(1, rightProductSpawn - 5);
    }
    
    public void updateLeftQuality () {
        leftProductQuality--;
        leftProductQuality = Math.max(1, leftProductQuality);
    }
    
    public void updateRightQuality () {
        rightProductQuality--;
        rightProductQuality = Math.max(1, rightProductQuality);
    }
    
    public void setBackground(){
        background = new GreenfootImage ("background.png");
        setBackground (background);
    }
    
    public void drawLabels(int leftStarting, int rightStarting){
        leftScoreLabel = new Label("$" + leftStarting + "/$" + winCond, labelSize);
        leftScore = leftStarting;
        addObject(leftScoreLabel, getWidth() / 32 * 3, labelY);
        
        rightScoreLabel = new Label("$" + rightStarting + "/$" + winCond, labelSize);
        rightScore = rightStarting;
        addObject(rightScoreLabel, getWidth() / 32 * 29, labelY);
    }
    
    public void drawCountdown(){
        leftBar = new SuperStatBar(barProgress, 0, null, getWidth() / 2, barHeight, 0, Color.GREEN, Color.GRAY);
        rightBar = new SuperStatBar(barProgress, 0, null, getWidth() / 2, barHeight, 0, Color.GREEN, Color.GRAY);
        rightBar.setRotation(180);
        addObject(leftBar, getWidth() / 4, 0);
        addObject(rightBar, getWidth() / 4 * 3, 0);
        
        GreenfootImage overlayColour = new GreenfootImage(getWidth(), getHeight());
        overlayColour.setColor(new Color(0, 0, 0, 150));
        overlayColour.fill();
        
        overlay = new BlankActor();
        overlay.setImage(overlayColour);
        addObject(overlay, getWidth() / 2, getHeight() / 2);
        
        countdownLabel = new Label(3, countdownSize);
        addObject(countdownLabel, getWidth() / 2, getHeight() / 2);
    }
    
    public void updateLeftScore(){
        leftScoreLabel.setValue("$" + leftScore + "/$" + winCond);
    }
    
    public void updateRightScore(){
        rightScoreLabel.setValue("$" + rightScore + "/$" + winCond);
    }
    
    public void changeLeftScore(int score){
        leftScore = leftScore + score;
        updateLeftScore();
    }
    
    public void changeRightScore(int score){
        rightScore = rightScore + score;
        updateRightScore();
    }
    
    public void updateCountdown(){
        barProgress--;
        leftBar.update(barProgress);
        rightBar.update(barProgress);
    }
    
    public void removeCountdown(){
        removeObject(leftBar);
        removeObject(rightBar);
        removeObject(countdownLabel);
        removeObject(overlay);
    }
    
    public void updateTimer(){
        timerLabel.setValue(timer / 60 + "s");
    }
    
    public void drawTimer(){
        timerLabel = new Label("0s", labelSize);
        addObject(timerLabel, getWidth() / 2, labelY);
    }
    
    public void checkWin(){
        if (leftScore >= winCond){
            Greenfoot.setWorld(new WinScreen("Left", rightScore, soundMan));
        }
        else if (rightScore >= winCond){
            Greenfoot.setWorld(new WinScreen("Right", leftScore, soundMan));
        }
    }
    
    public void canUpgradeLeft(){
        if (leftUpgradeCooldown > 0) {
            leftUpgradeCooldown--;
            return;
        }
        
        if (leftScore > minScoreBuy){
            if (leftMach.getBroken() && !leftRepair.getActivated()){
                leftPointer.activate(leftUpgradeX, repairY, leftRepair);
                leftUpgradeCooldown = upgradeCooldown;
                return;
            }
            if (Greenfoot.getRandomNumber(upgradeChance) == 0){
                if (rightBrokeLeft >= 0 && !rightMach.getBroken() && !leftBreak.getActivated()){
                    leftPointer.activate(leftUpgradeX, breakY, leftBreak);
                    leftUpgradeCooldown = upgradeCooldown;
                    return;
                }
                int rand = Greenfoot.getRandomNumber(4); // 0 Break, 1 Buy, 2 Quality, 3 Spawn
                if (rand == 0 && !rightMach.getBroken() && !leftBreak.getActivated()){
                    leftPointer.activate(leftUpgradeX, breakY, leftBreak);
                    leftBrokeRight = 900;
                } else if (rand == 1 && !leftBuy.getActivated()){
                    leftPointer.activate(leftUpgradeX, buyY, leftBuy);
                } else if (rand == 2 && !leftQuality.getActivated()){
                    leftPointer.activate(leftUpgradeX, qualityY, leftQuality);
                } else if (rand == 3 && !leftSpawnUpgrade.getActivated()) {
                    leftPointer.activate(leftUpgradeX, spawnUpgradeY, leftSpawnUpgrade);
                }
                leftUpgradeCooldown = upgradeCooldown;
                return;
            }
        }
    }
    
    public void canUpgradeRight(){
        if (rightUpgradeCooldown > 0) {
            rightUpgradeCooldown--;
            return;
        }
        
        if (rightScore > minScoreBuy){
            if (rightMach.getBroken() && !rightRepair.getActivated()){
                rightPointer.activate(rightUpgradeX, repairY, rightRepair);
                rightUpgradeCooldown = upgradeCooldown;
                return;
            }
            if (Greenfoot.getRandomNumber(upgradeChance) == 0){
                if (leftBrokeRight >= 0 && !leftMach.getBroken() && !rightBreak.getActivated()){
                    rightPointer.activate(rightUpgradeX, breakY, rightBreak);
                    rightUpgradeCooldown = upgradeCooldown;
                    return;
                }
                int rand = Greenfoot.getRandomNumber(4); // 0 Break, 1 Buy, 2 Quality, 3 Spawn
                if (rand == 0 && !leftMach.getBroken() && !rightBreak.getActivated()){
                    rightPointer.activate(rightUpgradeX, breakY, rightBreak);
                    rightBrokeLeft = 900;
                } else if (rand == 1 && !rightBuy.getActivated()){
                    rightPointer.activate(rightUpgradeX, buyY, rightBuy);
                } else if (rand == 2 && !rightQuality.getActivated()){
                    rightPointer.activate(rightUpgradeX, qualityY, rightQuality);
                } else if (rand == 3 && !rightSpawnUpgrade.getActivated()){
                    rightPointer.activate(rightUpgradeX, spawnUpgradeY, rightSpawnUpgrade);
                }
                rightUpgradeCooldown = upgradeCooldown;
                return;
            }
        }
    }

    public void addLeftPackager() {
        if (leftBoughtPackager) return;
        leftBoughtPackager = true;
    
        leftPackager = new Packager();
        addObject(leftPackager, leftPos, (getHeight() / 4 * 3) + 40);
    
        leftPackagerHitbox = new Hitbox();
        addObject(leftPackagerHitbox, leftPos, (getHeight() / 4 * 3) + 40);
    }
    
    public void addRightPackager() {
        if (rightBoughtPackager) return;
        rightBoughtPackager = true;
    
        rightPackager = new Packager();
        addObject(rightPackager, rightPos, (getHeight() / 4 * 3) + 40);
    
        rightPackagerHitbox = new Hitbox();
        addObject(rightPackagerHitbox, rightPos, (getHeight() / 4 * 3) + 40);
    }
    
    public void addLeftHandler () {
        if (leftBoughtHandler) return;
        leftBoughtHandler = true;
        
        leftHandler = new Handler();
        addObject(leftHandler, leftPos, (getHeight() / 4) - 40);
        
        leftHandlerHitbox = new Hitbox();
        addObject(leftHandlerHitbox, leftPos, (getHeight() / 4) - 40);
    }
    
    public void addRightHandler () {
        if (rightBoughtHandler) return;
        rightBoughtHandler = true;
        
        rightHandler = new Handler();
        addObject(rightHandler, rightPos, (getHeight() / 4) - 40);
        
        rightHandlerHitbox = new Hitbox();
        addObject(rightHandlerHitbox, rightPos, (getHeight() / 4) - 40);
    }
    
    public int leftMachinesRemaining () {
        int count = 0;
        if (leftBoughtPackager) count++;
        if (leftBoughtHandler) count++;
        return count;
    }
    
    public int rightMachinesRemaining () {
        int count = 0;
        if (rightBoughtPackager) count++;
        if (rightBoughtHandler) count++;
        return count;
    }
    
    public Machines getLeftMachine(){
        return leftMach;
    }
    
    public Machines getRightMachine(){
        return rightMach;
    }
    
    public SoundManager getSoundMan(){
        return soundMan;
    }
    
    public void act(){
        if (!gameStarted){
            startingTimer--;
            countdownLabel.setValue(startingTimer / 60 + 1);
            if (startingTimer <= 0){
                gameStarted = true;
                removeCountdown();
                drawTimer();
                //soundMan.playBgm();
                soundMan.playAmbience();
            }
            updateCountdown();
            return;
        }

        if (lastLeft >= spawnDelay) {
            if (Greenfoot.getRandomNumber(leftProductSpawn) == 0) {
                
                int rand = Greenfoot.getRandomNumber(leftProductQuality);
                
                if (rand == 0) {
                    addObject(new Metal(1, leftSpeed), leftPos, 0);
                } else if (rand == 1 || rand == 2) {
                    addObject(new Wood(1, leftSpeed), leftPos, 0);
                } else {
                    addObject(new Cardboard(1, leftSpeed), leftPos, 0);
                }
                
                lastLeft = 0;
            }
        }

        if (lastRight >= spawnDelay) {
            if (Greenfoot.getRandomNumber(rightProductSpawn) == 0) {
                
                int rand = Greenfoot.getRandomNumber(rightProductQuality);
                
                if (rand == 0) {
                    addObject(new Metal(2, rightSpeed), rightPos, 0);
                } else if (rand == 1 || rand == 2) {
                    addObject(new Wood(2, rightSpeed), rightPos, 0);
                } else {
                    addObject(new Cardboard(2, rightSpeed), rightPos, 0);
                }
                
                lastRight = 0;
            }
        }
        
        // Act from last product spawn
        lastLeft++;
        lastRight++;
        
        // Revenge countdown if one breaks the other machine
        leftBrokeRight--;
        rightBrokeLeft--;
        
        timer++;
        if (timer % 60 == 0){
            updateTimer();
        }
        
        canUpgradeLeft();
        canUpgradeRight();
        checkWin();
    }
    
    public int getLeftScore () {
        return leftScore;
    }
    
    public int getRightScore () {
        return rightScore;
    }
}
